### ISSUE TITLE
K8SSAND-940 ⁃ #186 - Scaling can trigger endless cleanup loop

### ISSUE THREAD

**Issue by berndocklin** [k8ssandra/cass-operator#186]
**What happened?**

After a scaling operation cluster went into a bad state of an endless loop of triggering cleanups, cleanup is triggered but is reported back as failed in EP, due to this error the API call `DatacenterScalingUp` state is not reset causing another multiple round of cleanups. 

```
{"level":"error","ts":1632913707.7406483,"logger":"reconciliation_handler","msg":"unable to perform request to Node Management Endpoint","requestNamespace":"prod","requestName":"xxxx-dc1","loopID":"64424726-be90-45af-98a8-2b018e71de1b","namespace":"prod","datacenterName":"xxxxx-dc1","clusterName":"xxxx-dse","error":"Post \"http://x.x.x.x:8080/api/v0/ops/keyspace/cleanup\": context deadline exceeded","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/datastax/cass-operator/operator/pkg/httphelper.callNodeMgmtEndpoint\n\t/cass-operator/operator/pkg/httphelper/client.go:349\ngithub.com/datastax/cass-operator/operator/pkg/httphelper.(*NodeMgmtClient).CallKeyspaceCleanupEndpoint\n\t/cass-operator/operator/pkg/httphelper/client.go:237\ngithub.com/datastax/cass-operator/operator/pkg/reconciliation.(*ReconciliationContext).cleanupAfterScaling\n\t/cass-operator/operator/pkg/reconciliation/reconcile_racks.go:2090\ngithub.com/datastax/cass-operator/operator/pkg/reconciliation.(*ReconciliationContext).CheckClearActionConditions\n\t/cass-operator/operator/pkg/reconciliation/reconcile_racks.go:2135\ngithub.com/datastax/cass-operator/operator/pkg/reconciliation.(*ReconciliationContext).ReconcileAllRacks\n\t/cass-operator/operator/pkg/reconciliation/reconcile_racks.go:2353\ngithub.com/datastax/cass-operator/operator/pkg/reconciliation.(*ReconciliationContext).calculateReconciliationActions\n\t/cass-operator/operator/pkg/reconciliation/handler.go:166\ngithub.com/datastax/cass-operator/operator/pkg/reconciliation.(*ReconcileCassandraDatacenter).Reconcile\n\t/cass-operator/operator/pkg/reconciliation/handler.go:269\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:88"}
```

**Did you expect to see something different?**

There should be a way to stop cleanups. It is understood that somehow the cleanup is wrongly reported as failing. However, there needs to be a way to get out of that loop.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Cass Operator version:

    `Insert image tag or Git SHA here`
    
    * Kubernetes version information:    `kubectl version`
    * Kubernetes cluster kind:```insert how you created your cluster: kops, bootkube, etc.

```

* Manifests:

```

insert manifests relevant to the issue

```

* Cass Operator Logs:

```

insert Cass Operator logs relevant to the issue here
```

**Anything else we need to know?**:



┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-940) by [Unito](https://www.unito.io)
┆Reviewer: John Sanda
┆fixVersions: cass-operator-1.9.0
┆friendlyId: K8SSAND-940
┆priority: Medium

**Comment by burmanm** [comment]
After the discussion in the meeting, here is my proposed approach:

* operator will spawn cleanupAfterScaling() to a goroutine and mark this part of the operation as done. The cleanupAfterScaling() will eject logging and potentially events to indicate if the cleanup has failed / succeeded. There will be no retries and the timeout for that operation is removed (but context is created to allow canceling). 
* The above approach works with older images of DSE/Cassandra also, without requiring changes to the management-api / Cassandra code.
* We should look into fixing the issue in Cassandra by making the process async (such as queueing it to the compaction queue instead of canceling all compactions and waiting for completion in a sync matter)
* We will also fix a bug in the cleanupAfterScaling() which stops the processing if first node succeeds as the operation should be ran on all of the nodes (serial).

**Comment by jsanda** [comment]
>There will be no retries and the timeout for that operation is removed (but context is created to allow canceling).

If the timeout is removed, do we fall back to HTTP defaults?

>We will also fix a bug in the cleanupAfterScaling() which stops the processing if first node succeeds as the operation should be ran on all of the nodes (serial)

It should be run on all nodes except the one that was added.

**Comment by jsanda** [comment]
>The above approach works with older images of DSE/Cassandra also, without requiring changes to the management-api / Cassandra code.

That is a plus but I think we should also look at making it async on the management-api side since getting changes pushed through in Cassandra is more involved and will take a lot longer. 

The other reason I would like to see the change on the management-api side is because I think it would be a bit more resilient. 
Doing it on the operator side means that if the operator pod goes down then the operation is aborted. That shouldn't be the case. The operation should able to continue to run so long as the Cassandra pod is up IMO.

**Comment by burmanm** [comment]
That would work as long as management-api can keep track of those jobs. Otherwise at cass-operator we're unable to track which pods have executed, which haven't and when should we reissue the cleanup command.

Also, we need to detect when management-api supports this new feature as there are Cassandra pods with non-functional and functional versions.

**Comment by rsds143** [comment]
I think this is a pretty nuanced approach and threads the needle. 

* yes, cleanup needs to be fixed to be less aggressive to shutting down existing work. However, this is also risky as we could get long-running compactions that block all compaction on the node for hours. We cannot count on this getting better since it is tricky to make cleanup less mean without creating new issues. Therefore, I would not expect a resolution on this front any time soon.
* no cleanup on added nodes: yes! Nice optimization.
* upgraded management-API great, with lots of baked images out there, as @burmanm noted, we would need to support two code paths for this. I think this is maybe ok, but part of me does wonder if auto cleanup is worth it or not. I get there is a long-term goal to remove all the complex details of Cassandra out via the operator, but I also sort of wonder if this should be an explicit command to the operator itself? Some CRD for creating a cleanup job? This way, the end-users still do not have to manage running cleanup on the cluster to control when cleanup happens.

**Comment by burmanm** [comment]
> no cleanup on added nodes: yes! Nice optimization.

This is not being removed. The cleanup will still be called in the ScalingUp process. 

> Cassandra out via the operator, but I also sort of wonder if this should be an explicit command to the operator itself? Some CRD for creating a cleanup job?

There is already a job that the user triggers, that's the scalingUp. If the cluster can't handle scale up process at that point of time, it should not be issued (and instead done during the maintenance window they might have).

**Comment by tlasica** [comment]
So if we and N nodes then it will be called on 1st...N-1th?

**Comment by burmanm** [comment]
Well, it will be called on every node, but the operation on that new node is noop.

**Comment by burmanm** [comment]
I think for 4.0 there's a better way. The Virtual Tables provide a view ``system.sstable_tasks`` which allows to fetch the status of compactions and cleanups. Modifying the management api to make the task go to background would allow us to check on the next reconcile if the pod has finished the cleanup task (by querying the virtual table) and if it has, move on to the next one. Fixing 4.0 itself to make this always async is of course another thing, but that's a slower approach to get this working.

For older deployments (and 3.11), the approach as done in PR #191 should be still used as a workaround.
