### ISSUE TITLE
K8SSAND-1124 ⁃ Update RedHat catalogs with latest release of cass-operator

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/cass-operator#251]
**What is missing?**
Recently a bunch of work was done to update bundles and publish the latest version of cass-operator to operator-hub, and updated release should also be published to the RedHat catalog for use with OpenShift.

**Why do we need it?**
To deploy the latest version on OpenShift.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1124) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1124
┆priority: Medium

**Comment by gmcbrien** [comment]
Hi - any update or ETA here please?
Thanks a lot

**Comment by burmanm** [comment]
We're waiting for Red Hat to do some work so we could publish it.

**Comment by gmcbrien** [comment]
> We're waiting for Red Hat to do some work so we could publish it.

Thanks for the fast reply. Any _approximate_ ETA.... weeks / months? Or let us know some more details and we can see if we can push Red Hat from our side.

**Comment by burmanm** [comment]
I hope next week, I received latest update from them yesterday indicating they're working on it.

**Comment by chrisob** [comment]
@burmanm Thanks for tracking this, I can see in the OCP 4.8 catalog cass-operator v1.9.0 is now available. 

However, OCP 4.7's catalog still lists 1.5.0 as the latest available. **Is it planned to make the updated version available on OCP 4.7's catalog**? (or is this something entirely up to RH?)

**Comment by burmanm** [comment]
@chrisob 1.10.1 should be available for 4.7 now. This is the last version that can target 4.7 however, given that there's a deprecation of PodDisruptionBudget, which forces us to update it from v1beta1 to v1. And that breaks 4.7 while keeping it as beta breaks 4.11.

**Comment by chrisob** [comment]
Thanks for the update @burmanm, from myself and a few others in my org :grin: Rgd. being stuck on cass-operator 1.10.1 on OCP 4.7 due to the PDB deprecation, makes sense & I think that's fine :+1: 

Digging into the RH certified operators repo, it looks like [these updates are still "pinned" to only be available on 4.8](https://github.com/redhat-openshift-ecosystem/certified-operators/pull/568/files#diff-2f579afa54f5475fe0beb05a87811ec06e4d818a89a748ef54c0efa2b0afd848R15).

What's your take on setting [`com.redhat.openshift.versions: v4.7-v4.8` (or maybe just `v4.7`?)](https://redhat-connect.gitbook.io/certified-operator-guide/ocp-deployment/operator-metadata/bundle-directory/managing-openshift-versions) to enable this in OCP 4.7's catalog?

**Comment by burmanm** [comment]
Well, that was unfortunate. I modified the script to push 4.7, but somehow managed to push 4.8 as requirement. I can't modify that version number, but I'll push 1.10.2 with the 4.7 modifications.

https://github.com/redhat-openshift-ecosystem/certified-operators/pull/579

That should be v4.7 - v4.10 support.

**Comment by burmanm** [comment]
Closing this as 1.10.2 should be merged and ready.
