### ISSUE TITLE
K8SSAND-1131 ⁃ How to deploy cassandra dc on multi aws region using cass-operator?

### ISSUE THREAD

**Issue by LafonteFull** [k8ssandra/cass-operator#252]
I have 2 eks cluster in ap-east region and eu-west region.
I deploy cassandra dc on each eks cluster using cass-operator and using aws-nlb for seeds params but the dc is not discoverable on `nodetool status` command.
what i missed?

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1131) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1131
┆priority: Medium

**Comment by jdonenine** [comment]
Hi @LafonteFull it's hard to say without specifics, but generally the key to multi-region deployment is the connectivity between pods in each region/cluster -- this can be particularly tricky with EKS in particular.  We have a blog post that isn't specific to the mulit-region deployment you're trying to do, but discusses a migration between regions that I think can give you some good insight into the requirements at play.  You can check that out here:

https://k8ssandra.io/blog/tutorials/cassandra-database-migration-to-kubernetes-zero-downtime/

Multi-region deployment is also something that we're working on more broadly in the newer k8ssandra-operator project.  The basic connectivity requirements remain the same, but we're working to make configuration and the management of seeds much easier, you might be interested in checking it out if you're in the exploration phase of things with your project.  

You can check that out here:

https://medium.com/building-the-open-data-stack/deploying-to-multiple-kubernetes-clusters-with-the-k8ssandra-operator-f7562bee1841

We also recently demo'd a multi-cloud deployment of K8ssandra taking advantage of the kubefed to simplify the cross-cluster networking pieces, that might be of interest as well.  

You can check that out here:

https://www.youtube.com/watch?v=dGvMEf21beM

Hopefully some of that helps!

**Comment by jsanda** [comment]
You need to set the `.spec.additionalSeeds` property in your second cassdc. It takes an array of IP addresses. If you have DNS across clusters, then you could specify the seed service for the value of `additionalSeeds`; otherwise, you will need to use IP addresses.

Managing the `additionalSeeds` property can be challenging due to the ephemeral nature of pods. k8ssandra-operator handles this for you. In fact, it doesn't populate `additionalSeeds` with IP addresses at all. A service is created for the additional seeds and k8ssandra-operator creates the endpoints in each remote k8s cluster and keeps them up to date.

Note that the kubefed mentioned by @jdonenine is not the upstream kubefed. It is an Amazon extension of it.
