### ISSUE TITLE
Enable CDC agent support for DSE

### ISSUE THREAD

**Issue by emerkle826** [k8ssandra/cass-operator#476]
**What happened?**
Attempting to enable CDC with DSE images fails. Currently, the code that enabled CDC assume that:
1) MCAC is always present and should be enabled via Java Agent (DSE has its own built-in MCAC and does not need the agent line in the startup config)
2) The Management API agent jarfile name is the same regardless of server version (it's currently different for DSE, but this should be resolved once this [PR](https://github.com/k8ssandra/management-api-for-apache-cassandra/pull/243) is merged and released)

The code that would need to change currently lives [here](https://github.com/k8ssandra/cass-operator/blob/master/pkg/cdc/generate_config.go#L94-L96).

**NOTE**: The fix for this issue should wait for the [Management API PR](https://github.com/k8ssandra/management-api-for-apache-cassandra/pull/243) to be merged and released.

**Comment by burmanm** [comment]
There's more to this than meets the eye. The DSE currently is intentionally prevented, as default DSE images do not have CDC plugin. 

Even if the management-api PR is merged, we need to know what we're using when trying to enable the feature. We can't poll mgmt-api and ask if this feature exists, as the change must happen before mgmt-api has started. And that leads to an issue, since there are two different DSE images, the ones built by the DSE team and the ones built by k8ssandra team. The default used in cass-operator is for now the official DSE images and they do not (and will not for now) have the changes from that mgmt-api PR.

Thus, we can only enable the CDC agent, if the image is from our k8ssandra repository and it has a version 6.8.31 or newer. If it's 6.8.31 from the official DSE, it should not be enabled. That needs both webhook validation as well as reconcile validation.

**Comment by emerkle826** [comment]
> and it has a version 6.8.31 or newer.

You are correct in that we can't enable it if the DSE image is not from the k8ssandra repository. However, the Management API PR above, when released, will create DSE images with the CDC agent for the current versions supported there [6.8.25, 6.8.26, 6.8.28, 6.8.29, 6.8.30 and 6.8.31]. It may be safe enough to ensure that the DSE image is from the k8ssandra repository and the Management API version is at least the version that will be released once the aforementioned PR is merged.

**Comment by jsanda** [comment]
I might also want to require setting some sort of feature flag or maybe an annotation on the CassandraDatacenter, to enable the functionality for DSE given the inconsistency across images.

**Comment by burmanm** [comment]
We can fail it through webhook validation, I don't think the annotation makes sense (we don't tend to use annotation for these types of things).

**Comment by Miles-Garnsey** [comment]
There isn't too much consensus on how we should move forward here by the look of it. 

It sounds like the proposals so far are:

1. Disable MCAC for DSE when enabling CDC.
2. Throw an error out of the webhook if a non-k8ssandra-built image is used.
3. Only enable CDC for DSE if a feature flag is set (I assume in cass-operator) or an annotation is set on the cassDC.

I want to start by outlining the baseline state; right now if you try to enable CDC on a DSE cluster the cluster will not start and will error out. By updating the logic to work with DSE (which, at present looks like just disabling MCAC) we are derisking DSE deployments via cass-operator.

In terms of using non-k8ssandra images, I think that is artificially limiting to users because many users will be building their own images or hosting on their own registries. There is no practical way to tell whether a particular image includes the CDC agent.

Is there a reason why we can't just move to using our own images (which do contain the CDC agent and which we are in control of) instead of the DataStax images?
