### ISSUE TITLE
Update nodeStatuses info when a pod is recreated

### ISSUE THREAD

**Issue by olim7t** [k8ssandra/cass-operator#652]
#638 added the `ip` and `rack` fields to `nodeStatuses`. However this information is not correctly refreshed when a pod is deleted and recreated: the pod IP might change, but the status keeps returning the old IP.

I think this is because I made the changes inside of the `if force || nodeStatus.HostID == "" { ... }` block. It's probably just a matter of moving them a couple of lines below.

On a side note, it would also be useful to have the CQL port alongside the IP, we can use the opportunity to add it (unless there is a reasonably easy way to infer it from the DC spec).

**Comment by burmanm** [comment]
> On a side note, it would also be useful to have the CQL port alongside the IP, we can use the opportunity to add it (unless there is a reasonably easy way to infer it from the DC spec).

We don't allow changing CQL port at the moment in cass-operator, that work would be relevant to ticket: https://github.com/k8ssandra/cass-operator/issues/242 and requires changes in the port definition codes, which are hardcoded everywhere, like: 

https://github.com/k8ssandra/cass-operator/blob/3dfaadcc62e24c710e0efbc86f6832be4c3c22ac/apis/cassandra/v1beta1/cassandradatacenter_types.go#L811

https://github.com/k8ssandra/cass-operator/blob/3dfaadcc62e24c710e0efbc86f6832be4c3c22ac/pkg/reconciliation/construct_service.go#L32

So that would be a PR of it's own, requiring design how all the port definitions can be modified, tested, wired to the mgmt-api and supported there also (I'm not sure how much mgmt-api even supports these).
